apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    project: roboshop
    component: mysql
    tier: backend
    environment: dev
  annotations:
    description: "This pod is created to demo annotations.."
    jenkins: "https://jenkins.com"
spec:
  containers:
  - name: nginx
    image: nginx